### ISSUE TITLE
Need update npm package

### ISSUE THREAD

**Issue by ToPal** [emech-en/mongo-morgan#4]
Hi!

You updated code at https://github.com/emech-en/mongo-morgan/commit/ad6839fc683486c5af8fee136bd36cc1dac8f3ea, but didn't updated npm package.

After `npm i --save mongo-morgan` I see in package.json `"mongo-morgan": "^2.0.1"` and in node_modules/mongo-morgan/package.json:
![image](https://user-images.githubusercontent.com/1311093/31877940-0a6c0e6c-b7e1-11e7-96f0-24d5545b75c5.png)

As you can see, mongodb version is old and strict. It makes some problems in my project (for example, this sort of things: https://github.com/Automattic/mongoose/issues/1884)

Please, update npm package

**Comment by emech-en** [comment]
Now it's updated. 

Thank you.

**Comment by emech-en** [comment]
Now it's updated.

Thank you.
